### ISSUE TITLE
Need assistance regarding the implementation of IAUnet for VideoReID

### ISSUE THREAD

**Issue by FatimaZulfiqar** [blue-blue272/ImgReID-IAnet#5]
I want to train IAUnet for video reid datasets. I need assistance in this regard. Will you please share the complete github repo for the same?

**Comment by blue-blue272** [comment]
I will release the code this week.

**Comment by FatimaZulfiqar** [comment]
Thank you. Will be waiting

**Comment by FatimaZulfiqar** [comment]
Hi will you please also share the dataset loader for DukeMTMC-VideoReID?

**Comment by FatimaZulfiqar** [comment]
Are part masks also generated for videoreid dataset? Need assistance in dataset loader for video reid dataset
